/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;
import myview.TelaPrincipal;
import conecta.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus Amorim da Cruz & Pedro Sant'Anna
 */
public class Log_In extends javax.swing.JFrame {

         /*
          * Variáveis públicas estáticas utilizadas para que possamos utilizá-las na hora do cadastro, pegando o id do usuário nesse momento para colocá-lo na chave estrangeira no futuro.
         */  
    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public static String idUser = "";
    public static String nameUser = "";
    public static String profileUser= "";

    public Log_In() {
        initComponents();
        connection = conectar.conector();
    }   
   
   /*
     * Metódo utilizado para realizar o Log In dos usuários cadastrados na tabela tb_user.
   */ 
    public void logar(){
        String sql = "SELECT * FROM tb_user WHERE name_user = ? AND password_user = ?";
        try{
            pst = connection.prepareStatement(sql);
            pst.setString(1,UserName.getText());
            pst.setString(2,UserPassword.getText());                         
            rs = pst.executeQuery();
           
           if(UserName.getText().isEmpty() || UserPassword.getText().isEmpty()){
               JOptionPane.showMessageDialog(null, "Preencha o nome de usuário e a senha.");
               UserName.grabFocus();
           }else{
                if(rs.next()){
                   idUser    = rs.getString(1);
                   nameUser = rs.getString(2);
                   profileUser = rs.getString(5);
                
                   String perfil    = rs.getString(5);
                   
                    TelaBoasVindas welcome = new TelaBoasVindas();
                    welcome.setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Usuário ou senha incorreta.");
                    UserName.setText(null);
                    UserPassword.setText(null);
                    UserName.grabFocus();
                }
            }                        
        }
        catch (Exception e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSignUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        UserPassword = new javax.swing.JPasswordField();
        BtnLogIn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setLocation(new java.awt.Point(500, 150));

        BtnSignUp.setText("Criar Conta");
        BtnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignUpActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuário");

        jLabel2.setText("Senha");

        UserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UserNameKeyTyped(evt);
            }
        });

        UserPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UserPasswordKeyTyped(evt);
            }
        });

        BtnLogIn.setText("Entrar");
        BtnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogInActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 24)); // NOI18N
        jLabel3.setText("MyView");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnLogIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnSignUp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel3)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnLogIn)
                .addGap(18, 18, 18)
                .addComponent(BtnSignUp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignUpActionPerformed
        /*
         * Botão utilizado para voltar à tela de cadastro.
        */ 
        Sign_Up signup = new Sign_Up();
        signup.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnSignUpActionPerformed

    private void UserPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserPasswordKeyTyped
        /*
         * Evento utilizado para limitar o tamanho da senha que o usuário pode escrever no campo texto. 
        */  
        Character ch = evt.getKeyChar();
        int QtdDigitos = UserPassword.getText().length();
        if (QtdDigitos >= 8){
            evt.consume();
        }
    }//GEN-LAST:event_UserPasswordKeyTyped

    private void BtnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogInActionPerformed
        /*
         * Botão utilizado para chamar o metódo logar()
        */  
        logar();
    }//GEN-LAST:event_BtnLogInActionPerformed

    private void UserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserNameKeyTyped
        /*
         * Evento utilizado para limitar o tamanho do nome que o usuário pode escrever no campo texto. 
        */  
        Character ch = evt.getKeyChar();
        int QtdDigitos = UserName.getText().length();
        if (QtdDigitos >= 40){
            evt.consume();
        }
    }//GEN-LAST:event_UserNameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log_In().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogIn;
    private javax.swing.JButton BtnSignUp;
    private javax.swing.JTextField UserName;
    private javax.swing.JPasswordField UserPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
