/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;
import conecta.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus Amorim da Cruz & Pedro Sant'Anna
 */
public class Sign_Up extends javax.swing.JFrame {

    /**
     * Creates new form Sign_UP
     */
    public Sign_Up() {
        initComponents();
        connection = conectar.conector();
    }

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    
   /*
    * Função utilizada para cadastrar um novo usuário no tabela de usuário(tb_user). 
    */
    public void SignUp (){
        String sql = "INSERT INTO tb_user (name_user, email_user, password_user, profile_user, cpf_user) VALUES (?,?,?,?,?);";
        try{
            pst = connection.prepareStatement(sql);
            pst.setString(1,CadName.getText());
            pst.setString(2,CadEmail.getText());
            pst.setString(3,CadPassword.getText());
            pst.setString(4,CadProfile.getSelectedItem().toString());
            pst.setString(5,CadCpf.getText());
            
            if (CadName.getText().isEmpty() || CadEmail.getText().isEmpty() || CadPassword.getText().isEmpty() || CadCpf.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
                CadName.grabFocus();
            }
            else{
                int add = pst.executeUpdate();

                if (add > 0){
                    JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
                    CadName.setText(null);
                    CadEmail.setText(null);
                    CadPassword.setText(null);
                    CadCpf.setText(null);
                    CadName.grabFocus();
                }
            }
        }
        catch (Exception e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadProfile = new javax.swing.JComboBox();
        BtnBack2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnSignUp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CadName = new javax.swing.JTextField();
        CadEmail = new javax.swing.JTextField();
        CadCpf = new javax.swing.JTextField();
        CadPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        setLocation(new java.awt.Point(500, 150));

        CadProfile.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "User", "Admin" }));

        BtnBack2.setText("Voltar");
        BtnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBack2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome de usuário");

        BtnSignUp.setText("Cadastrar");
        BtnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignUpActionPerformed(evt);
            }
        });

        jLabel2.setText("Email");

        jLabel3.setText("Senha");

        jLabel4.setText("Pefil");

        jLabel5.setText("CPF");

        CadName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CadNameKeyTyped(evt);
            }
        });

        CadEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CadEmailKeyTyped(evt);
            }
        });

        CadCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CadCpfKeyTyped(evt);
            }
        });

        CadPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CadPasswordKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 24)); // NOI18N
        jLabel6.setText("MyView");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(CadName)
                            .addComponent(CadEmail)
                            .addComponent(CadCpf)
                            .addComponent(CadProfile, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CadPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel6)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CadName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CadEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CadPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CadProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CadCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBack2)
                    .addComponent(BtnSignUp))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBack2ActionPerformed
       /*
        * Botão utilizado para voltar para a tela de Log In.
       */  
        Log_In login = new Log_In();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBack2ActionPerformed

    private void BtnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignUpActionPerformed
         /*
          * Botão utilizado para chamar o método SignUp(), encarregado de cadastrar novas informações na tabela de usuários (tb_user)
         */
        SignUp();
    }//GEN-LAST:event_BtnSignUpActionPerformed

    private void CadPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CadPasswordKeyTyped
        /*
         * Evento utilizado para limitar o tamanho da senha que o usuário pode escrever no campo texto. 
        */ 
        Character ch = evt.getKeyChar();
        int QtdDigitos = CadPassword.getText().length();
        if (QtdDigitos >= 8){
            evt.consume();
        }
    }//GEN-LAST:event_CadPasswordKeyTyped

    private void CadCpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CadCpfKeyTyped
         /*
          * Evento utilizado para limitar o tamanho do CPF que o usuário pode escrever no campo texto.
         */
        Character ch = evt.getKeyChar();
        int QtdDigitos = CadCpf.getText().length();
        if (QtdDigitos >= 11){
            evt.consume();
        }
        
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_CadCpfKeyTyped

    private void CadEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CadEmailKeyTyped
         /*
          * Evento utilizado para limitar o tamanho do Email que o usuário pode escrever no campo texto.
         */
        Character ch = evt.getKeyChar();
        int QtdDigitos = CadEmail.getText().length();
        if (QtdDigitos >= 80){
            evt.consume();
        }
    }//GEN-LAST:event_CadEmailKeyTyped

    private void CadNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CadNameKeyTyped
         /*
          * Evento utilizado para limitar o tamanho do nome que o usuário pode escrever no campo texto.
         */
        Character ch = evt.getKeyChar();
        int QtdDigitos = CadName.getText().length();
        if (QtdDigitos >= 40){
            evt.consume();
        }
    }//GEN-LAST:event_CadNameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_Up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack2;
    private javax.swing.JButton BtnSignUp;
    private javax.swing.JTextField CadCpf;
    private javax.swing.JTextField CadEmail;
    private javax.swing.JTextField CadName;
    private javax.swing.JPasswordField CadPassword;
    private javax.swing.JComboBox CadProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
